ecryptfs: Add `CONFIG_SDP` guard of variables definition
While compiling Kernel without `CONFIG_SDP` is set,
we would see these errors:

  ../fs/ecryptfs/file.c: In function 'ecryptfs_unlocked_ioctl':
  ../fs/ecryptfs/file.c:728:10: error: unused variable 'sdp_rc' [-Werror=unused-variable]
       long sdp_rc = -ENOTTY;
            ^
  ../fs/ecryptfs/file.c: In function 'ecryptfs_compat_ioctl':
  ../fs/ecryptfs/file.c:800:10: error: unused variable 'sdp_rc' [-Werror=unused-variable]
       long sdp_rc = -ENOIOCTLCMD;
            ^

Since these variables are only used if `CONFIG_SDP` is set,
it will remain unused if SDP is disabled.

Add `CONFIG_SDP` guard so we're only defining these variables
if `CONFIG_SDP` is set.

Signed-off-by: Hendra Manudinata <hendra@manudinata.me>